[package]
name = "rust-s3"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-sdk-s3 = { version = "1.32.0", features = ["rt-tokio"] }
tokio = { version = "1.38.0", features = ["full"] }
aws-config = { version = "1.5.0", features = ["behavior-version-latest"] }
